### ISSUE TITLE
Notice: The certificate for TLS must be .cer extension

### ISSUE THREAD

**Issue by elliott10** [shadowsocks/v2ray-plugin-android#14]
* The certificate for TLS must be .cer extension.
Content-Type: `application/pkix-cert`

* And if you have encountered error:
`E v2ray   : v2ray.com/core/transport/internet/tls: failed to load system root certificate > v2ray.com/core/transport/internet/tls: append cert to root`
Please refer to this: https://github.com/shadowsocks/v2ray-plugin/pull/128

**Comment by jeffshead** [comment]
I have Shadowsocks and v2ray-plugin installed on a CentOS 7 server. It is set up with Caddy and has a Let’s Encrypt SSL cert (i.e., ws+tls+web).

How do you install the cert in the Android Shadowsocks app? I installed the v2ray Plugin and under the v2ray settings, is an option to add the Certificate for TLS verification. I have downloaded the cert to the phone and tried to select it but the v2ray plugin will not import it. I gave the cert a .cer extension and I also tried .crt.

Also, since it's a Let's Encrypt cert, it's only good for 90 days. Is it necessary to add the cert to the Android v2ray plugin? It seems to work without it.

**Comment by elliott10** [comment]
Download shadowsocks on GooglePlay, then download v2ray-plugin on [F-droid](https://f-droid.org/en/packages/com.github.shadowsocks.plugin.v2ray).
Because the v2ray-plugin on GooglePlay does not work properly.

After configure a server with a certificate from Let’s Encrypt, copy the xxx.pem certificate to Android directory /sdcard/Download/. Rename the xxx.pem file to xxx.**cer**

In shadowsocks app profile, select the v2ray plugin with websocket-tls transport mode, your server domain name. Click "**BROWSE...**" in "Certificate for TLS verification", then select the /sdcard/Download/xxx.**cer**

v2ray-plugin from F-droid works fine in Android 8.
